version: '3.9'
services:
  listener:
    image: revere:latest
    build: .
    tty: true
    stdin_open: true
    env_file:
      - .env
      - docker.env
    links:
      - db
    networks:
      - default
    command: ['listen', '-l', 'discord', '-n', 'discord']

  jobs:
    image: revere:latest
    build: .
    env_file:
      - .env
      - docker.env
    links:
      - db
    networks:
      - default
    command: ['start']

  yfinance:
    image: yfinance:latest
    build: apis/yfinance
    networks:
      - default
    ports:
      - 5000:5000

  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: revere
      POSTGRES_USER: revere
      POSTGRES_PASSWORD: revere
    networks:
      - default
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

networks:
  default:
    driver: bridge
