version: '3.9'
services:
  revere:
    image: revere:latest
    build: .
    tty: true
    stdin_open: true
    env_file:
      - .env
      - docker.env
    links:
      - db
    networks:
      - default
    command: ['listen', '-l', 'discord', '-n', 'discord']

  scheduler:
    image: revere:latest
    build: .
    env_file:
      - .env
      - docker.env
    links:
      - db
    networks:
      - default
    command: ['runscheds']

  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: revere
      POSTGRES_USER: revere
      POSTGRES_PASSWORD: revere
    ports:
      - 5432:5432
    networks:
      default:
        aliases:
          - db
    volumes:
      - ./pgdata:/var/lib/postgresql/data

networks:
  default:
    driver: bridge
